### PR TITLE
Update strings.xml, Irish and associated English

### PR DESCRIPTION
**Pull request by marcasoduinn**
First draft of updates to Irish translations. 
TBD review with other Irish speakers.

### CODE REVIEW

**Comment by marcasoduinn** [comment]
Are both "strings.xml" part of this one "Pull request"?

**Comment by thecosmicfrog** [comment]
Hey @marcasoduinn,

Great work! Just one thing - I think you created a Pull Request against your **own master branch** instead of mine (thecosmicfrog/LuasataGlance/master). No big deal. You can close this and re-create against mine.

I haven't done this myself (on GitHub at least) for a while, so no sweat!

All the best,
Aaron

**Comment by marcasoduinn** [comment]
Closing this Pull Request back to the "marcasoduinn-irish-1" branch.

**Comment by marcasoduinn** [comment]
Do I have to merge first?

**Comment by marcasoduinn** [comment]
It looks like I merged into "master".

**Comment by marcasoduinn** [comment]
...merged onto "master" of the version that I forked from Aaron's main.  I can now delete the "marcasoduinn-irish-1" branch of that fork, but I still need to open a pull request from my "fork" to the main repository...

...correct?

**Pull request merged**
